### ISSUE TITLE
Builder Base bug

### ISSUE THREAD

**Issue by Sunclear7** [xbebenk/MBR_xbebenkMod#156] opened 2024-01-05 14:28 UTC
I'm only having a problem with BB. It's not making attacks or upgrades, it's just visiting the BB and returning to the main village.
(
I tried using bluestacks 5.20, and nox 7.0.5.9. neither of them worked on BB

**Comment by daregod** [comment] 2024-01-05 19:53
I'm seeing the same problem on some profiles. What debug mode to enable to understand where the problem is?

```
[1:48:26] [1] Trying to Switch to Builder Base
[1:48:42] [1] Trying to Switch to Normal Village
```

**Comment by Sunclear7** [comment] 2024-01-05 20:40
I've had this problem for a long time, I've never been able to solve it

my logs:

2: D [2024-01-05 11:13:18.747] _RunFunction: BuilderBase BEGIN
2: D [2024-01-05 11:13:19.024] Using Image to Check if isOnBuilderBase
2: L [2024-01-05 11:13:19.038] [1] Trying to Switch to Builder Base
2: D [2024-01-05 11:13:19.078] Using Image to Check if isOnBuilderBase
2: D [2024-01-05 11:13:19.083] GetVillageSize check for image stoneDS-116-418_0_92.xml
2: D [2024-01-05 11:13:19.164] findImage : stoneDS Found in: 119,415
2: D [2024-01-05 11:13:19.164] Found stone image at 119, 415: stoneDS-116-418_0_92.xml
2: D [2024-01-05 11:13:19.165] stone: 119|415|116|418|DS|stoneDS-116-418_0_92.xml
2: D [2024-01-05 11:13:19.166] GetVillageSize check for image treeDS-575-79_0_93.xml
2: D [2024-01-05 11:13:19.238] findImage : treeDS Found in: 581,73
2: D [2024-01-05 11:13:19.239] Found tree image at 581, 73: treeDS-575-79_0_93.xml
2: D [2024-01-05 11:13:19.239] tree: 581|73|575|79|notused|treeDS-575-79_0_93.xml
2: D [2024-01-05 11:13:19.240] bCenterVillage = True
2: D [2024-01-05 11:13:19.241] Centering Village (SwitchBetweenBases) by: x=5, y=-3
2: D [2024-01-05 11:13:21.311] Using Image to Check if isOnBuilderBase
2: D [2024-01-05 11:13:21.317] GetVillageSize check for image stoneDS-116-418_0_92.xml
2: D [2024-01-05 11:13:21.403] findImage : stoneDS Found in: 119,415
2: D [2024-01-05 11:13:21.404] Found stone image at 119, 415: stoneDS-116-418_0_92.xml
2: D [2024-01-05 11:13:21.404] stone: 119|415|116|418|DS|stoneDS-116-418_0_92.xml
2: D [2024-01-05 11:13:21.405] GetVillageSize check for image treeDS-575-79_0_93.xml
2: D [2024-01-05 11:13:21.478] findImage : treeDS Found in: 581,73
2: D [2024-01-05 11:13:21.479] Found tree image at 581, 73: treeDS-575-79_0_93.xml
2: D [2024-01-05 11:13:21.480] tree: 581|73|575|79|notused|treeDS-575-79_0_93.xml
2: D [2024-01-05 11:13:21.481] bCenterVillage = False
2: D [2024-01-05 11:13:36.673] Using Image to Check if isOnMainVillage
2: L [2024-01-05 11:13:36.680] [1] Trying to Switch to Normal Village
2: D [2024-01-05 11:13:37.255] Waiting for DLL async function SearchMultipleTilesBetweenLevels ...
2: D [2024-01-05 11:13:37.913] [SwitchBetweenBases] ZoomOutHelperBB: Found TreeBL-693-170 on [649,172]
2: D [2024-01-05 11:13:37.914] ZoomOutHelperBB: Centering village by -44,2
2: L [2024-01-05 11:13:41.048] Switch From Builder Base To Normal Village Success
2: D [2024-01-05 11:13:41.257] _RunFunction: BuilderBase END

**Comment by xbebenk** [comment] 2024-01-06 03:41
before you report, update your bot
be sure you have default/jungle/magic scenery only
be sure you have enabled option on BuilderBase tab
enable debug log from debug tab
run Builderbase() on debug tab

**Comment by xbebenk** [comment] 2024-01-06 03:41
[10:38:09 AM] Saving your setting...
[10:38:10 AM] Done!
[10:38:12 AM] DebugSetlog enabled
[10:38:17 AM] Run Function : builderbase()
[10:38:17 AM] checkChatTabPixel: Found ChatTab
[10:38:17 AM] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: 424E15
[10:38:18 AM] DLL Call succeeded 
[10:38:18 AM] checkChatTabPixel: Found ChatTab
[10:38:18 AM] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 466,17 Found: 8AA330
[10:38:18 AM] DLL Call succeeded 
[10:38:18 AM] Using Image to Check if isOnBuilderBase
[10:38:18 AM] DLL Call succeeded 
[10:38:18 AM] checkChatTabPixel: Found ChatTab
[10:38:19 AM] _checkMainScreenImage(1), Expected: A7D7F1, Tolerance: 20 at X,Y: 382,5 Found: A7D7F1
[10:38:19 AM] [1] Trying to Switch to Builder Base
[10:38:19 AM] checkChatTabPixel: Found ChatTab
[10:38:19 AM] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: 424E15
[10:38:19 AM] DLL Call succeeded 
[10:38:19 AM] checkChatTabPixel: Found ChatTab
[10:38:20 AM] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 466,17 Found: 8AA330
[10:38:20 AM] DLL Call succeeded 
[10:38:20 AM] Using Image to Check if isOnBuilderBase
[10:38:20 AM] DLL Call succeeded 
[10:38:20 AM] GetVillageSize check for image stoneDS-116-418_0_92.xml
[10:38:20 AM] findImage : stoneDS Found in: 115,413
[10:38:20 AM] Found stone image at 115, 413: stoneDS-116-418_0_92.xml
[10:38:20 AM] stone: 115|413|116|418|DS|stoneDS-116-418_0_92.xml
[10:38:20 AM] GetVillageSize check for image treeDS-575-79_0_93.xml
[10:38:20 AM] findImage : treeDS Found in: 569,77
[10:38:20 AM] Found tree image at 569, 77: treeDS-575-79_0_93.xml
[10:38:20 AM] tree: 569|77|575|79|notused|treeDS-575-79_0_93.xml
[10:38:20 AM] LRTB: 82,770,58,577
[10:38:20 AM] GetVillageSize, Scenery : DS : Default, Zoom:0.988089067862026
[10:38:20 AM] Stone2tree = 564.811472971292
[10:38:20 AM] Reference = 571.62
[10:38:20 AM] ZoomLevel = 0.988089067862026
[10:38:20 AM] Stone2tree:564.81 Reference:571.62 checkZoomOffset: -6.81
[10:38:20 AM] GetVillageSize measured: 564.811472971292, Zoom factor: 0.988089067862026, Offset: -5, -4
[10:38:20 AM] bCenterVillage = True
[10:38:20 AM] Centering Village (SwitchBetweenBases) by: x=-5, y=-4
[10:38:20 AM] aVillageCenteringCoord : [636,500]
[10:38:22 AM] checkChatTabPixel: Found ChatTab
[10:38:22 AM] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: 424E15
[10:38:23 AM] DLL Call succeeded 
[10:38:23 AM] checkChatTabPixel: Found ChatTab
[10:38:23 AM] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 466,17 Found: 8AA330
[10:38:23 AM] DLL Call succeeded 
[10:38:23 AM] Using Image to Check if isOnBuilderBase
[10:38:23 AM] DLL Call succeeded 
[10:38:23 AM] GetVillageSize check for image stoneDS-116-418_0_92.xml
[10:38:24 AM] findImage : stoneDS Found in: 115,413
[10:38:24 AM] Found stone image at 115, 413: stoneDS-116-418_0_92.xml
[10:38:24 AM] stone: 115|413|116|418|DS|stoneDS-116-418_0_92.xml
[10:38:24 AM] GetVillageSize check for image treeDS-575-79_0_93.xml
[10:38:24 AM] findImage : treeDS Found in: 569,77
[10:38:24 AM] Found tree image at 569, 77: treeDS-575-79_0_93.xml
[10:38:24 AM] tree: 569|77|575|79|notused|treeDS-575-79_0_93.xml
[10:38:24 AM] LRTB: 82,770,58,577
[10:38:24 AM] GetVillageSize, Scenery : DS : Default, Zoom:0.988089067862026
[10:38:24 AM] Stone2tree = 564.811472971292
[10:38:24 AM] Reference = 571.62
[10:38:24 AM] ZoomLevel = 0.988089067862026
[10:38:24 AM] Stone2tree:564.81 Reference:571.62 checkZoomOffset: -6.81
[10:38:24 AM] GetVillageSize measured: 564.811472971292, Zoom factor: 0.988089067862026, Offset: -5, -4
[10:38:24 AM] bCenterVillage = False
[10:38:24 AM] Centered Village Offset (SwitchBetweenBases): -5, -4, change: 0, 0
[10:38:24 AM] DLL Call succeeded BoatBadge_0_93.xml|BoatSailDS_0_93.xml
[10:38:24 AM] BC1 Found: BoatBadge Level:0, using 187,486
[10:38:25 AM] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: FEE5BA
[10:38:25 AM] Switch From Normal Village To Builder Base Success
[10:38:25 AM] [BuilderBase] Check BuilderBase Main Screen
[10:38:25 AM] checkMainScreen : BuilderBase
[10:38:26 AM] checkChatTabPixel: Found ChatTab
[10:38:26 AM] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: FEE5BA
[10:38:26 AM] [BuilderBase] Main Screen located
[10:38:26 AM] Notify | NotifyPendingActions()
[10:38:26 AM] Builder Base Report
[10:38:27 AM] checkChatTabPixel: Found ChatTab
[10:38:27 AM] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: FEE5BA
[10:38:28 AM]  [G]: 1 442 309 [E]: 2 507 580[T]: 2 786
[10:38:28 AM] Updating Builder Base Resource Values
[10:38:29 AM] checkChatTabPixel: Found ChatTab
[10:38:29 AM] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: FEE5BA
[10:38:29 AM]  [G]: 1 442 309 [E]: 2 507 580[T]: 2 786

**Comment by Sunclear7** [comment] 2024-01-06 10:42
2: L [2024-01-06 07:39:59.150] Run Function : builderbase()
2: L [2024-01-06 07:39:59.336] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:39:59.342] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: 0D0D0D
2: D [2024-01-06 07:39:59.357] DLL Call succeeded 
2: L [2024-01-06 07:39:59.361] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:39:59.364] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 466,17 Found: 343910
2: D [2024-01-06 07:39:59.378] DLL Call succeeded 
2: D [2024-01-06 07:39:59.379] Using Image to Check if isOnBuilderBase
2: D [2024-01-06 07:39:59.384] DLL Call succeeded 
2: L [2024-01-06 07:39:59.388] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:39:59.392] _checkMainScreenImage(1), Expected: A7D7F1, Tolerance: 20 at X,Y: 382,5 Found: A7D8F0
2: L [2024-01-06 07:39:59.396] [1] Trying to Switch to Builder Base
2: L [2024-01-06 07:39:59.403] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:39:59.407] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: 0D0D0D
2: D [2024-01-06 07:39:59.421] DLL Call succeeded 
2: L [2024-01-06 07:39:59.425] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:39:59.429] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 466,17 Found: 343910
2: D [2024-01-06 07:39:59.443] DLL Call succeeded 
2: D [2024-01-06 07:39:59.444] Using Image to Check if isOnBuilderBase
2: D [2024-01-06 07:39:59.449] DLL Call succeeded 
2: D [2024-01-06 07:39:59.451] GetVillageSize check for image stoneDS-116-418_0_92.xml
2: D [2024-01-06 07:39:59.543] findImage : stoneDS Found in: 75,448
2: D [2024-01-06 07:39:59.621] Found stone image at 75, 448: stoneDS-116-418_0_92.xml
2: D [2024-01-06 07:39:59.623] stone: 75|448|116|418|DS|stoneDS-116-418_0_92.xml
2: D [2024-01-06 07:39:59.625] GetVillageSize check for image treeDS-575-79_0_93.xml
2: D [2024-01-06 07:39:59.695] findImage : treeDS Found in: 588,69
2: D [2024-01-06 07:39:59.696] Found tree image at 588, 69: treeDS-575-79_0_93.xml
2: D [2024-01-06 07:39:59.697] tree: 588|69|575|79|notused|treeDS-575-79_0_93.xml
2: D [2024-01-06 07:39:59.699] LRTB: 82,770,58,577
2: D [2024-01-06 07:39:59.700] GetVillageSize, Scenery : DS : Default, Zoom:1.11580523434532
2: D [2024-01-06 07:39:59.701] Stone2tree = 637.816588056473
2: D [2024-01-06 07:39:59.702] Reference = 571.62
2: D [2024-01-06 07:39:59.704] ZoomLevel = 1.11580523434532
2: D [2024-01-06 07:39:59.705] Stone2tree:637.82 - Reference:571.62 = 66.2 > 35
2: L [2024-01-06 07:40:00.884] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:40:00.897] ZoomOutBlueStacks5()
2: D [2024-01-06 07:40:00.899] aVillageCenteringCoord : [777,235]
2: L [2024-01-06 07:40:01.060] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:40:01.063] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: 0D0D0D
2: D [2024-01-06 07:40:01.077] DLL Call succeeded 
2: L [2024-01-06 07:40:01.080] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:40:01.084] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 466,17 Found: 343910
2: D [2024-01-06 07:40:01.097] DLL Call succeeded 
2: D [2024-01-06 07:40:01.099] Using Image to Check if isOnBuilderBase
2: D [2024-01-06 07:40:01.104] DLL Call succeeded 
2: D [2024-01-06 07:40:01.107] GetVillageSize check for image stoneDS-116-418_0_92.xml
2: D [2024-01-06 07:40:01.193] findImage : stoneDS Found in: 75,448
2: D [2024-01-06 07:40:01.194] Found stone image at 75, 448: stoneDS-116-418_0_92.xml
2: D [2024-01-06 07:40:01.195] stone: 75|448|116|418|DS|stoneDS-116-418_0_92.xml
2: D [2024-01-06 07:40:01.197] GetVillageSize check for image treeDS-575-79_0_93.xml
2: D [2024-01-06 07:40:01.264] findImage : treeDS Found in: 588,69
2: D [2024-01-06 07:40:01.266] Found tree image at 588, 69: treeDS-575-79_0_93.xml
2: D [2024-01-06 07:40:01.267] tree: 588|69|575|79|notused|treeDS-575-79_0_93.xml
2: D [2024-01-06 07:40:01.268] LRTB: 82,770,58,577
2: D [2024-01-06 07:40:01.270] GetVillageSize, Scenery : DS : Default, Zoom:1.11580523434532
2: D [2024-01-06 07:40:01.271] Stone2tree = 637.816588056473
2: D [2024-01-06 07:40:01.272] Reference = 571.62
2: D [2024-01-06 07:40:01.274] ZoomLevel = 1.11580523434532
2: D [2024-01-06 07:40:01.275] Stone2tree:637.82 - Reference:571.62 = 66.2 > 35
2: L [2024-01-06 07:40:02.540] ZoomOut() : DefaultZoomOut
2: L [2024-01-06 07:40:02.826] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:40:02.831] _checkMainScreenImage(1), Expected: A7D7F1, Tolerance: 20 at X,Y: 382,5 Found: A7D8F0
2: D [2024-01-06 07:40:03.438] DLL Call succeeded treeDS-575-79_0_93.xml
2: D [2024-01-06 07:40:03.439] BC1 Found: treeDS-575-79 Level:0, using 571,77
2: D [2024-01-06 07:40:03.440] [DefaultZoomOut] ZoomOutHelper: Found treeDS-575-79 on [571,77]
2: D [2024-01-06 07:40:03.442] Centering village by -4,-2
2: D [2024-01-06 07:40:05.216] DLL Call succeeded BoatBadge_0_93.xml|BoatSailDS_0_93.xml
2: D [2024-01-06 07:40:05.220] BC1 Found: BoatBadge Level:0, using 192,483
2: D [2024-01-06 07:40:06.673] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: D [2024-01-06 07:40:09.145] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: D [2024-01-06 07:40:11.586] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: D [2024-01-06 07:40:14.083] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: D [2024-01-06 07:40:16.446] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: L [2024-01-06 07:40:19.911] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:40:19.915] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: D [2024-01-06 07:40:19.931] DLL Call succeeded 
2: L [2024-01-06 07:40:19.934] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:40:19.938] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 466,17 Found: FDE4B8
2: L [2024-01-06 07:40:19.941] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:40:19.945] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: D [2024-01-06 07:40:19.959] DLL Call succeeded 
2: L [2024-01-06 07:40:19.962] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:40:19.966] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 466,17 Found: FDE4B8
2: L [2024-01-06 07:40:19.968] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:40:19.972] _checkMainScreenImage(1), Expected: A7D7F1, Tolerance: 20 at X,Y: 382,5 Found: 494B5C
2: D [2024-01-06 07:40:19.985] DLL Call succeeded 
2: D [2024-01-06 07:40:19.987] Using Image to Check if isOnMainVillage
2: D [2024-01-06 07:40:19.992] DLL Call succeeded 
2: L [2024-01-06 07:40:19.995] [1] Trying to Switch to Normal Village
2: L [2024-01-06 07:40:19.998] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:40:20.001] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: D [2024-01-06 07:40:20.015] DLL Call succeeded 
2: L [2024-01-06 07:40:20.017] checkChatTabPixel: Found ChatTab
2: D [2024-01-06 07:40:20.021] _checkMainScreenImage(1), Expected: FEE4B9, Tolerance: 20 at X,Y: 466,17 Found: FDE4B8
2: D [2024-01-06 07:40:20.576] Waiting for DLL async function SearchMultipleTilesBetweenLevels ...
2: D [2024-01-06 07:40:21.123] DLL Call succeeded TreeBL-693-170_0_95.xml
2: D [2024-01-06 07:40:21.125] BC1 Found: TreeBL-693-170 Level:0, using 663,161
2: D [2024-01-06 07:40:21.127] [SwitchBetweenBases] ZoomOutHelperBB: Found TreeBL-693-170 on [663,161]
2: D [2024-01-06 07:40:21.128] ZoomOutHelperBB: Centering village by -30,-9
2: D [2024-01-06 07:40:22.826] DLL Call succeeded BoatFront_0_92.xml
2: D [2024-01-06 07:40:22.827] BC1 Found: BoatFront Level:0, using 639,129
2: D [2024-01-06 07:40:24.263] SwitchBetweenBases, Expected: A7D7F1, Tolerance: 20 at X,Y: 382,5 Found: A7D8F0
2: L [2024-01-06 07:40:24.278] Switch From Builder Base To Normal Village Success
2: L [2024-01-06 07:40:24.281] Result : 0
2: L [2024-01-06 07:40:24.283] [25125ms]

**Comment by xbebenk** [comment] 2024-01-06 17:54
opengl?

**Comment by Sunclear7** [comment] 2024-01-06 17:57
yes

**Comment by xbebenk** [comment] 2024-01-06 17:58
can you try with dx ?

**Comment by Sunclear7** [comment] 2024-01-06 18:06
gave the same error

**Comment by xbebenk** [comment] 2024-01-06 18:19
2: D [2024-01-06 07:40:06.673] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: D [2024-01-06 07:40:09.145] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: D [2024-01-06 07:40:11.586] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: D [2024-01-06 07:40:14.083] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A
2: D [2024-01-06 07:40:16.446] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: DDAD8A

bot not found expected color

try this:
manually go to builderbase
_CheckPixel($aIsOnBuilderBase, True, Default, "SwitchBetweenBases")
_CheckPixel($aIsOnBuilderBase1, True, Default, "SwitchBetweenBases")
_GetPixelColor($aIsOnBuilderBase[0], $aIsOnBuilderBase[1], True)
_GetPixelColor($aIsOnBuilderBase1[0], $aIsOnBuilderBase1[1], True)

**Comment by Sunclear7** [comment] 2024-01-06 18:23
Could you explain better what I have to do?

**Comment by Sunclear7** [comment] 2024-01-06 18:47
I manually went to the builder base and used debug builderbase()

apparently everything worked well, the bot used the laboratory, clock tower and made resource reports

**Comment by xbebenk** [comment] 2024-01-07 00:52
> Could you explain better what I have to do?

you manually go to builderbase and do each command on debug tab

**Comment by Sunclear7** [comment] 2024-01-07 01:46
I tested the four commands in the base builder

2: L [2024-01-06 22:43:46.187] Run Function : _CheckPixel($aIsOnBuilderBase, True, Default, "SwitchBetweenBases")
2: D [2024-01-06 22:43:46.193] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 476,17 Found: 7B5C50
2: L [2024-01-06 22:43:46.194] Result : False
2: L [2024-01-06 22:43:46.195] [0ms]
2: D [2024-01-06 22:43:57.057] Restore bot window to 873, 22, caller: GUIControl_WM_SHELLHOOK
2: D [2024-01-06 22:43:58.049] Restore bot window to 873, 22, caller: GUIControl_WM_NCACTIVATE
2: L [2024-01-06 22:44:02.091] Run Function : _CheckPixel($aIsOnBuilderBase1, True, Default, "SwitchBetweenBases")
2: D [2024-01-06 22:44:02.103] SwitchBetweenBases, Expected: FEE4B9, Tolerance: 20 at X,Y: 466,17 Found: FEE5BA
2: L [2024-01-06 22:44:02.104] Result : True
2: L [2024-01-06 22:44:02.104] [15ms]
2: D [2024-01-06 22:44:16.293] Restore bot window to 873, 22, caller: GUIControl_WM_SHELLHOOK
2: D [2024-01-06 22:44:17.834] Restore bot window to 873, 22, caller: GUIControl_WM_NCACTIVATE
2: L [2024-01-06 22:44:21.138] Run Function : _GetPixelColor($aIsOnBuilderBase[0], $aIsOnBuilderBase[1], True)
2: L [2024-01-06 22:44:21.151] Result : 7B5C50
2: L [2024-01-06 22:44:21.152] [15ms]
2: D [2024-01-06 22:44:28.154] Restore bot window to 873, 22, caller: GUIControl_WM_SHELLHOOK
2: D [2024-01-06 22:44:29.359] Restore bot window to 873, 22, caller: GUIControl_WM_NCACTIVATE
2: L [2024-01-06 22:44:32.209] Run Function : _GetPixelColor($aIsOnBuilderBase1[0], $aIsOnBuilderBase1[1], True)
2: L [2024-01-06 22:44:32.224] Result : FEE5BA
2: L [2024-01-06 22:44:32.225] [15ms]

**Comment by xbebenk** [comment] 2024-01-07 02:10
thanks.. 
now need your capture from photo button

**Comment by Sunclear7** [comment] 2024-01-07 02:15
![2024-01-06_23 13 08](https://github.com/xbebenk/MBR_xbebenkMod/assets/155748000/a1cbfb37-46eb-455d-a274-cd2cce4bf419)

**Comment by xbebenk** [comment] 2024-01-07 02:18
thanks, will fixed on next commit

**Comment by Sunclear7** [comment] 2024-01-07 02:20
ok, thank you

**Comment by Sunclear7** [comment] 2024-01-08 12:53
Thank you in advance for your work, the bot is able to go to the builder base normally. It's collecting resources, attacking, using laboratory. however, the bot is unable to detect whether there are free master builders and the bot is also unable to perform the checkmainscreen.

logs:

2: L [2024-01-08 09:46:53.696] [BuilderBase] Check BuilderBase Main Screen
2: D [2024-01-08 09:46:53.698] checkMainScreen : BuilderBase
2: D [2024-01-08 09:46:56.130] Search: Unplaced Building Not Found!
2: D [2024-01-08 09:46:56.296] Using Image to Check if isOnMainVillage
2: D [2024-01-08 09:46:56.351] findImage imgloc search returned no results in 300,38|566,38|566,75|300,75 for 'C:\Users\Meee\Desktop\MBR_xbebenkMod-dev_1.2.5\imgxml\other\Maintenance_0_90.xml' !
2: D [2024-01-08 09:46:56.352] ClickAway(): on X:236, Y:17
2: L [2024-01-08 09:46:56.352] Click 236,17,1,0 #0000 | Away
2: D [2024-01-08 09:46:56.399] minitouch: d 0 8992 824 1, speed=10, delay=15
2: D [2024-01-08 09:46:56.399] CheckObstacles[1] Result = False
2: D [2024-01-08 09:46:57.402] checkMainScreen : BuilderBase
2: D [2024-01-08 09:46:59.874] Search: Unplaced Building Not Found!
2: D [2024-01-08 09:47:00.045] Using Image to Check if isOnMainVillage
2: D [2024-01-08 09:47:00.100] findImage imgloc search returned no results in 300,38|566,38|566,75|300,75 for 'C:\Users\Meee\Desktop\MBR_xbebenkMod-dev_1.2.5\imgxml\other\Maintenance_0_90.xml' !
2: D [2024-01-08 09:47:00.100] ClickAway(): on X:241, Y:20
2: L [2024-01-08 09:47:00.101] Click 241,20,1,0 #0000 | Away
2: D [2024-01-08 09:47:00.145] minitouch: d 0 9182 969 1, speed=10, delay=15
2: D [2024-01-08 09:47:00.146] CheckObstacles[2] Result = False
2: D [2024-01-08 09:47:01.154] checkMainScreen : BuilderBase
2: D [2024-01-08 09:47:02.293] WaitforPixel Result: True [824|40]
2: L [2024-01-08 09:47:02.294] checkObstacles: Found FullScreenWindow to close
2: D [2024-01-08 09:47:04.355] CheckObstacles[3] Result = False
2: D [2024-01-08 09:47:05.357] checkMainScreen : BuilderBase
2: D [2024-01-08 09:47:07.803] Search: Unplaced Building Not Found!
2: D [2024-01-08 09:47:07.983] Using Image to Check if isOnMainVillage
2: D [2024-01-08 09:47:08.056] findImage imgloc search returned no results in 300,38|566,38|566,75|300,75 for 'C:\Users\Meee\Desktop\MBR_xbebenkMod-dev_1.2.5\imgxml\other\Maintenance_0_90.xml' !
2: D [2024-01-08 09:47:08.057] ClickAway(): on X:235, Y:8
2: L [2024-01-08 09:47:08.058] Click 235,8,1,0 #0000 | Away
2: D [2024-01-08 09:47:08.121] minitouch: d 0 8954 388 1, speed=10, delay=15
2: D [2024-01-08 09:47:08.123] CheckObstacles[4] Result = False
2: D [2024-01-08 09:47:09.130] checkMainScreen : BuilderBase
2: D [2024-01-08 09:47:09.726] Waiting for DLL async function SearchMultipleTilesBetweenLevels ...
2: D [2024-01-08 09:47:12.268] Search: Unplaced Building Not Found!
2: D [2024-01-08 09:47:12.449] Using Image to Check if isOnMainVillage
2: D [2024-01-08 09:47:12.514] findImage imgloc search returned no results in 300,38|566,38|566,75|300,75 for 'C:\Users\Meee\Desktop\MBR_xbebenkMod-dev_1.2.5\imgxml\other\Maintenance_0_90.xml' !
2: D [2024-01-08 09:47:12.515] ClickAway(): on X:231, Y:9
2: L [2024-01-08 09:47:12.516] Click 231,9,1,0 #0000 | Away
2: D [2024-01-08 09:47:12.555] minitouch: d 0 8801 436 1, speed=10, delay=15
2: D [2024-01-08 09:47:12.556] CheckObstacles[5] Result = False
2: D [2024-01-08 09:47:13.560] checkMainScreen : BuilderBase
2: D [2024-01-08 09:47:15.966] Search: Unplaced Building Not Found!
2: D [2024-01-08 09:47:16.133] Using Image to Check if isOnMainVillage
2: D [2024-01-08 09:47:16.202] findImage imgloc search returned no results in 300,38|566,38|566,75|300,75 for 'C:\Users\Meee\Desktop\MBR_xbebenkMod-dev_1.2.5\imgxml\other\Maintenance_0_90.xml' !
2: D [2024-01-08 09:47:16.203] ClickAway(): on X:236, Y:14
2: L [2024-01-08 09:47:16.204] Click 236,14,1,0 #0000 | Away
2: D [2024-01-08 09:47:16.252] minitouch: d 0 8992 679 1, speed=10, delay=15
2: D [2024-01-08 09:47:16.253] CheckObstacles[6] Result = False
2: L [2024-01-08 09:47:16.254] Waiting for Main Screen
2: L [2024-01-08 09:47:16.308] waitMainScreen: MainScreen Located
2: L [2024-01-08 09:47:16.309] [BuilderBase] Main Screen not located
2: L [2024-01-08 09:47:16.316] Collecting Resources on Builders Base
2: D [2024-01-08 09:47:17.504] Waiting for DLL async function SearchMultipleTilesBetweenLevels ...
2: D [2024-01-08 09:47:18.162] [Default] ZoomOutHelperBB: Found TreeBL-693-170 on [657,164]
2: D [2024-01-08 09:47:18.163] ZoomOutHelperBB: Centering village by -36,-6
2: L [2024-01-08 09:47:20.973] Builder Base Report
2: L [2024-01-08 09:47:21.149]  [G]: 457 064 [E]: 181 823[T]: 1 405
2: L [2024-01-08 09:47:21.266] CleanBBYard: Try removing obstacles
2: L [2024-01-08 09:47:21.267] Master Builder Not Available
2: L [2024-01-08 09:47:21.804] Updating Builder Base Resource Values
2: L [2024-01-08 09:47:22.008]  [G]: 457 064 [E]: 181 823[T]: 1 405
2: L [2024-01-08 09:47:22.045] Builder Base Gold Storages are > 90% : 457 064
2: L [2024-01-08 09:47:22.179] Builder Base Gold Storages are > 90% : 457 064
2: L [2024-01-08 09:47:22.383] Master Builder Not Available
2: L [2024-01-08 09:47:22.384] Free Master Builder : 0
2: L [2024-01-08 09:47:22.385] [BuilderBase] Check BuilderBase Main Screen
2: D [2024-01-08 09:47:22.386] checkMainScreen : BuilderBase
2: D [2024-01-08 09:47:24.834] Search: Unplaced Building Not Found!

**Closed** 2024-01-08 14:26 UTC

**Comment by xbebenk** [comment] 2024-01-08 14:46
yes
